pkg/keys/constants.go
=> Add constant strings for common database secrets

pkg/client.go, pkg/client_test.go, pkg/interfaces.go, pkg/mocks/secret_manager.go, pkg/providers/vault/secret_manager.go, pkg/providers/vault/secret_manager_test.go
=> Updated API to modify several keys and values at once.

pkg/keys/constants.go
Corrected constant key used for database username information to be
consistent with the rest of the system
=> Update database constant username

Dockerfile.build, Jenkinsfile, go.mod
=> Update relevant files in go-mod-secrets for Go 1.13 compiler.

go.mod, pkg/listener/poll.go, pkg/listener/poll_test.go, pkg/providers/vault/client.go, pkg/providers/vault/client_test.go, pkg/token/authtokenloader/methods.go, pkg/token/authtokenloader/methods_test.go, secrets/factory.go, secrets/factory_test.go
Module is a V0 Go module
Issue Number:  #80
Module is now a V2 Go module
=> refactor: Make module a V2 Go Module

go.mod, internal/pkg/vault/request.go
Close #119
Signed-off-by: weichou <weichou1229@gmail.com>
Issue Number: #119 
Manual upgrade core-contracts lib to v2.0.0-dev.100 for resolving the V2 package changes.
=> build: Upgrade core-contracts lib to v2.0.0-dev.100

go.mod
Using dev version of Core Contracts
Issue Number: n/a
Using released 2.0.0 version of Core Contracts
=> build: Update to released Core Contracts

.github/Contributing.md, .github/PULL_REQUEST_TEMPLATE.md
Add the missing Contributing.md and updated the PR template to the newly approved template.
=> ci: Add Contributing.md and update PR template

pkg/types/config.go
This is in support of
https://github.com/edgexfoundry/go-mod-bootstrap/issues/273
https://github.com/edgexfoundry/edgex-docs/pull/587
See Testing Instructions here: https://github.com/edgexfoundry/go-mod-bootstrap/pull/276 
**N/A**
=> feat: Add SecretsFile config setting

go.mod, go.sum
**N/A for build PR**
**N/A for build PR**
=> build: Update to released go-mod-core-contracts 2.1.0

.golangci.yml, Makefile, internal/pkg/vault/client.go, internal/pkg/vault/constants.go, pkg/requestor.go, pkg/token/authtokenloader/methods_test.go, pkg/types/config.go
Fixes #129
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
N/A
```make test```
=> feat(security): Enable gosec and default linter set

go.mod, go.sum
=> build: Update to use v2.2.0 released go-mods

go.mod, go.sum, vendor/modules.txt
=> build: Update to 2.1.1 released go-mods

Makefile, go.mod
=> build: Upgrade to Go 1.18

.github/dependabot.yml, go.mod, go.sum
=> build: Latest go-mods and daily DependaBot

go.mod, go.sum
Signed-off-by: Chris Hung <chris@iotechsys.com>
=> build: bump go-mod-core-contracts

go.mod, go.sum
=> build: Update to use released go-mods

Makefile, go.mod, internal/pkg/vault/client.go, internal/pkg/vault/secrets.go, internal/pkg/vault/secrets_test.go, pkg/requestor.go, pkg/token/authtokenloader/methods.go, pkg/token/fileioperformer/methods.go
<link to docs PR> 
make sure v1.51.2 of linter is installed
make test
verify no format or linter issues
=> build: Update to Go 1.20 and linter v1.51.2

CHANGELOG.md, go.mod, go.sum
=> docs: Update changelog for 3.0 and use released Core Contracts

go.mod, go.sum
=> build: Update to latest go-mods

Makefile, go.mod
=> build: Upgrade to go 1.21 and linter 1.54.2

go.mod, go.sum
=> feat: Update go.mod for 3.1.0

internal/pkg/vault/management.go, internal/pkg/vault/management_test.go
=> fix: health check return status code 200

go.mod, go.sum
=> build: Latest core contracts

Makefile, go.mod
Upgrade to go-1.23, Linter1.61.0
Run `make test`.
=> build: Upgrade to go-1.23, Linter1.61.0

go.mod, go.sum, vendor/modules.txt
=> build: Update to new go-mod-contracts 4.0.1 for odessa
