pkg/providers/vault/config.go
pkg/providers/vault/errors.go
pkg/providers/vault/secret_manager.go
pkg/providers/vault/secret_manager_test.go

Fix #7
Add functionality to allow the underlying HTTP client to use a Root CA
cert so that the HTTP client can communicate via HTTPS with a
self-signed cert.
Add new 'ErrCaRootCert' error for communicating cert errors to the
caller.

Add TLS configuration support to secret client

---

pkg/providers/vault/config.go
pkg/providers/vault/constants.go
pkg/providers/vault/secret_manager.go
pkg/providers/vault/secret_manager_test.go

Fix #17
Update the SecretConfig and Vault SecretClient to support Vault's notion
of Namespaces. The SecretConfig has been updated to contain a
configuration property which allow users to specify the Namespace to
operate under when interacting with the Vault SecretStore. The
SecretClient has been updated to provide the Namespace information in
the appropriate header when interacting with the Vault HTTP API

Add Vault Namespace support within SecretClient

---

pkg/listener/poll.go
pkg/listener/poll_test.go
pkg/listener/types.go

Fix #16
Add new 'InMemoryCacheListener' which adds functionality for
pro-actively polling a secret store for updates.
Create new 'listener' package which houses different implementations for
obtaining updates from a secret store.
Add tests for new logic

Create Listener for getting secret updates

---

pkg/providers/vault/config.go
pkg/providers/vault/constants.go
pkg/providers/vault/secret_manager.go
pkg/providers/vault/secret_manager_test.go
pkg/types.go

Fix #18
Remove the SecretConfig's provider field which was previously used to
identify the SecretClient implementation which should be use during
creation. This is not necessary as there is currently only one provider
for Vault and this generalization is most likely a concern for consumers
of the go-mod-secrets module as this still would not solve the issue of
abstracting the creation of SecretClients since there could be clients
which live outside of this module.

Remove provider configuration property

---

pkg/providers/vault/config.go
pkg/providers/vault/secret_manager.go

Fix #25
Add field for server name in SecretConfig and update the SecretClient
constructor to properly apply field in the underlying HTTP client.

Add functionality for TLSConfig ServerName info

---

pkg/client.go
pkg/providers/vault/secret_manager.go
pkg/providers/vault/secret_manager_test.go
pkg/types.go

Fix #24
Add logic to check the HTTP response code received when requesting
secrets from the secret store. Previously only HTTP errors would be
treated as an error where we should be treating non 200 responses as an
error.

Add response code checking to Vault SecretClient

---

pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/providers/vault/config.go

Allow a SecretClient to be created that retries HTTP requests that are not 2XX. Note that this behavior is optional, and needs to be opt-in by the calling client.
This enables clients of go-mod-secrets to easily block waiting for their secrets to be available.
Also include a proposed implementation of "infinite" blocking by setting the AdditionalRetryAttempts to a negative number, but error out for now, so as to not complicate testing.
Finally, update the tests to check the number of calls to Do() that are made when getting secrets under various situations.
To test this change IRL, see https://github.com/edgexfoundry/docker-edgex-mongo/pull/59 and the testing instructions there.

pkg/provides/vault/many: allow specifying retry logic

---

pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/providers/vault/config.go
pkg/providers/vault/interfaces.go

This addresses feedback from @AnthonyMBonafide on PR #36.
I did _not_ refactor this to take a string and do time.Parse, but if there's a strong opinion on this I can change this as well.
Also some minor drive-by changes to make this fall in line with go-linting (though note that some things go lint complains about aren't changable without breaking APIs :crying_cat_face: see `HttpConfig` -> `HTTPConfig`)
Lastly I added some drive-by changes to the doc-comment, see how the license currently shows up in the godoc: https://godoc.org/github.com/edgexfoundry/go-mod-secrets/pkg/providers/vault.

vault/client.go: refactor retry loop to GetSecrets instead of getAllKeys

---

pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/providers/vault/config.go

It is simpler for clients of go-mod-secrets to just provide a string here since in many cases the SecretConfig struct will be built verbatim from a configuration.toml file, where we don't have complex types like time.Duration (or at least a usable version of that - time.Duration serializes as an int64 in nanoseconds which is very unusable to specify in the configuration.toml).
This means we need to do the parsing of the string here if it exists and error in the case parsing fails.
Also add some tests for this functionality. A followup-PR to docker-edgex-mongo and edgex-go will be filed in short order with more testing information.
docker-edgex-mongo PR: https://github.com/edgexfoundry/docker-edgex-mongo/pull/67
See https://github.com/edgexfoundry/edgex-go/issues/2092 and …

pkg/providers/vault: change RetryWaitPeriod to string, do parsing here

---

pkg/client.go
pkg/listener/poll.go
pkg/listener/poll_test.go
pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/types.go

- Add a new StoreSecrets API with a provided path to call
- Update the InMemoryListener to also store secrets for unit testing
Fixes #39 
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

Add a new API to store secret

---

go.mod
pkg/token/authtokenloader/interface.go
pkg/token/authtokenloader/methods.go
pkg/token/authtokenloader/methods_test.go
pkg/token/authtokenloader/mocks/mock.go
pkg/token/authtokenloader/mocks/mock_test.go
pkg/token/authtokenloader/types.go
pkg/token/fileioperformer/interface.go
pkg/token/fileioperformer/methods.go
pkg/token/fileioperformer/methods_test.go
pkg/token/fileioperformer/mocks/mock.go
pkg/token/fileioperformer/mocks/mock_test.go

Fix #43
Move the security features related to getting a token for the secret
client since this project handles security related functionality.
Rename the directory from 'security' to 'token' to better represent its
place in this project.

Migrate Security Features From go-mod-bootstrap

---

pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/providers/vault/errors.go
pkg/providers/vault/factory.go
pkg/providers/vault/interfaces.go
pkg/providers/vault/mocklogger.go
pkg/providers/vault/models.go

Fixes issue #34 of go-mod-secrets.
The background process is periodically checking the Vault service token's TTL every half of token's TTL.
If the same token is given again, the go context will cancel the previous context and re-create a new one to keep it alive and preventing from creating multiple or too many background contexts for the same token.
The Vault's token is only renewable if it is periodic token (ie. the token period is > 0) and renewable is true.
If the TTL of token is already <= half of token's period when the call is invoked, it will renew right away before the periodic timer kicks off.
The `NewSecretClient` constructor is now taking a reference to a loggingClient interface implementation in order to log any progress, status, and potential error occurring in the …

Implement token refresh background process [issue #34]

---

pkg/client.go
pkg/providers/vault/client.go
pkg/providers/vault/config.go
pkg/providers/vault/config_test.go

initially it returned the path to the secrets in the secret store
BuildSecretsPathURL() added to return path to the secrets in the secret store
Closes: #49
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>

fix BuildURL() in SecretConfig to return url to the secret provider

---

go.mod
pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
pkg/providers/vault/config.go
pkg/providers/vault/config_test.go

Paths with trailing slash are sent to Vault
Issue Number: #56
Trailing slash if exists is removed when build Vault URL
no

fix: Remove trailing slash from vault URL to avoid 400 error

---

go.mod
pkg/providers/vault/client_test.go

Unit tests use logger factory method that has been removed in latest go-mod-core-contracts
Issue Number:  #76
Unit tests now use logger.NewMockClient()
no

refactor: Resolve compiler errors in unit test when using latest go-mod-core-contracts

---

go.mod
pkg/providers/vault/client.go
pkg/providers/vault/client_test.go
secrets/factory.go
secrets/factory_test.go

Consuming V0 Go Module version of go-mod-secrets
Issue Number:  #81
Now consume V2 Go Module version of go-mod-secrets

refactor: Consume V2 go-mod-secrets

---

internal/pkg/vault/management.go
pkg/listener/poll_test.go
secrets/interfaces.go
secrets/mocks/SecretClient.go

`SecretClient` interface doesn't contain `GenerateConsulToken`
Implementation exists, just needs to be exposed through SecretClient interface
Issue Number: #100
`SecretClient` interface now contains `GenerateConsulToken`
no

feat: Add GenerateConsulToken API to SecretClient interface

---

internal/pkg/vault/mock.go
internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go
pkg/types/messages.go
secrets/factory_test.go

Fix the issue as to token-self lookup API response returning `TokenMetadata` and it should be wrapped inside `"data"` JSON sub-structure
Closes: #102
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
- [x ] Bugfix
Currently, the token-self uses the wrong JSON structure information
Issue Number: #102 
Fix the JSON structure for token-self lookup to use the right JSON structure information and also fix the unit tests.
- [x ] No

fix(security): Fix JSON structure of token self response

---

Makefile
internal/pkg/vault/client.go
internal/pkg/vault/client_test.go
internal/pkg/vault/management_test.go
internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go
pkg/listener/poll.go
pkg/types/config.go
secrets/factory_test.go

Remove all codes related to retry attempts
Fixes: #115
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Refactoring (no functional changes, no api changes)
unnecessary retry code in the current GetSecrets and StoreSecrets API implementation
Issue Number: #115 
Remove these retry code from both GetSecrets and StoreSecrets APIs
- [x ] Yes
**The configuration entries: 
`AdditionalRetryAttempts`, `RetryWaitPeriod`, `RetryWaitPeriodTime`  got removed and thus all services use these items will need …

refactor!: clean up retry code for GetSecrets and StoreSecrets APIs

---

internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go

Issue: https://github.com/edgexfoundry/go-mod-secrets/issues/145
According to this [official http client documentation](https://golang.org/pkg/net/http/#Client.Do), `If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close.`. The Response Body must be closed when the returned error is nil. And we don't need check whether the Response Body is nil.

fix: close response Body when the returned error is nil

---

internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go

* fix: close response Body when the returned error is nil
Signed-off-by: gao270615179 <270615179@qq.com>
* fix: add InMemoryMockCaller response body
Signed-off-by: gao270615179 <270615179@qq.com>
Cherry pick 3ba02e4013d11d8a0b0741f59debb32a9114f29d from main
make test

fix: close response Body when the returned error is nil (#146)

---

internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go
pkg/errors.go

Signed-off-by: Kyle Morton <kylex.f.morton@intel.com>

feat: added error handling for status 404

---

internal/pkg/vault/constants.go
internal/pkg/vault/management.go
internal/pkg/vault/management_test.go
internal/pkg/vault/models.go
internal/pkg/vault/request.go
internal/pkg/vault/secrets.go
internal/pkg/vault/secrets_test.go
pkg/listener/poll_test.go
secrets/interfaces.go
secrets/mocks/SecretClient.go
secrets/mocks/SecretStoreClient.go

This set of changes enables secret store tokens to be identity-based.
Instead of issuing anonymous Vault tokens with attached policy,
this commit adds additional methods to create Vault-based
identities and authenticate to these identities using
programmable auth methods. This is important step to "deprivilege"
Vault usage, as creating raw tokens requires "sudo" ability in Vault,
whereas identity auth is a user operation. Additionally,
vault-based identity can be attested (as a JWT) and verified.
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
Please check if your PR fulfills the following …

feat: Enabling hooks for Vault identity features

---

internal/pkg/vault/management.go
internal/pkg/vault/management_test.go

fix: CheckIdentityKeyExists was comparing to constant

---

pkg/constants.go

Late-change due to regression failure. 
Git psudoversion for testing is github.com/bnevis-i/go-mod-secrets v3.0.0-20230524152540-f3ad386fe291
Tested override in device-virtual and edgex-go, and this seems to resolve the issue.

fix!: Missed /v3 change prior to EdgeX 3.0 code freeze

---

internal/pkg/vault/management.go

Closes edgex-go#4621
See testing instructions in https://github.com/edgexfoundry/edgex-go/issues/4621.  Basically, create a service key with _1, _2, etc at the end.

fix(security): Allow underscores in service keys / Vault usernames
